apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector: 
    matchLabels:
      app: db
  replicas: 1 
  template:
    metadata:
      labels: 
        app: db
    spec:
      containers:
      - image: postgres:latest
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 5432
        env:   
         - name: POSTGRES_PASSWORD
           value: "vulnado"
         - name: POSTGRES_DB
           value: "vulnado"
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
